### ISSUE TITLE
Breaks with TabsOnEdit eminiarts/nova-tabs

### ISSUE THREAD

**Issue by cord** [codenco-dev/nova-grid-system#14]
Layout is broken in combination with 

`use TabsOnEdit`

from https://novapackages.com/packages/eminiarts/nova-tabs

workaround for usage on detail view: use `->sizeOnDetail()`

**Comment by renzo-s** [comment]
That's because there is another wrapper involved with the tabs. Adding:

```css
.relationship-tabs-panel.flex {
    display: block;
}
```

Looks like a fix for this.
